project:
  type: website
  output-dir: docs

website:
  title: "Emma's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: blog.qmd
        text: Projects
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    googlefonts: ["Nunito Sans", "Inter"]